### PR TITLE
match new r2bin struct type

### PR DESCRIPTION
**Pull request by lowlyw**
https://github.com/radareorg/radare2/commit/4a75b94b495207b158ebeb3397ab550cf261e76e renamed `o` to `bo`, follow that change so it builds

**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some documentation

**Description**

`r_bin_file_t.o` was renamed to `r_bin_file_t.bo`, follow this change so that it can build again.

### CODE REVIEW

**Comment by trufae** [comment]
Please wrap this change with an if to keep backward compat. Thanks!

**Comment by lowlyw** [comment]
what would the if be checking? when r2ghidra is built there's no `-DVERSION=blah` or anything, is there?

**Comment by lowlyw** [comment]
nvm, updated, should work now

**Comment by trufae** [comment]
Beautiful <3

**Pull request merged**
